spring:
  application:
    name:
      em-music-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/EMBackEnd
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  error:
    include-stacktrace: always
em-music:
  security:
    is-test: true
  storage:
    basePath: C:\programing\EmMusic\back-end\em-music-backend\build